version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - './docker/data/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './app/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  php:
    environment:
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
      - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
      - XDEBUG_IDKEY=${XDEBUG_IDKEY}
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './app/:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
